-- leases.meta — what a lease holder is, beyond that it holds the lease.
--
-- Added for node presence (`node:{id}`), which is the fleet's only
-- membership read. A node needs more from its peers than "you exist":
-- it needs their ROLES, because a node that does not run seats must not
-- count in the seat denominator (it would shrink everyone's share and
-- strand the difference), and their LABELS, because that is what a
-- seat's `role.placement` selector matches against. See
-- `crewlet.seat.placement`.
--
-- Additive, which is the only kind of change this table takes (see
-- `017_leases.sql`): an older build never selects the column, so a
-- mixed-version fleet keeps working, and `NodeProfile.from_meta` reads a
-- missing payload as the old behaviour — a node that does everything and
-- carries no labels.
--
-- Not used for seat or worker leases today. It is deliberately general
-- rather than a `roles`/`labels` pair of columns: the next thing a
-- holder needs to advertise should not need another migration on a table
-- whose schema evolution is append-only forever.

ALTER TABLE leases ADD COLUMN IF NOT EXISTS meta JSONB NOT NULL DEFAULT '{}'::jsonb;
