-- An adoption row no longer says whether its ledger loss was folded.
--
-- 0030 gave `statelog_adoption` a `ledger_folded` column so the engine could
-- carry, once at boot, the adoptions a build from before the operation ledger
-- travelled had recorded into that ledger's watermark. No such build is
-- supported: every row this build writes is an adoption whose ledger travelled
-- with its watermark, so the fold had nothing to carry and is gone, and a
-- column nothing reads is a claim that some reader still cares. The table is
-- this node's adoption HISTORY and nothing else.
--
-- 0030 IS NOT EDITED: `schema_migrations` keys on the filename, so a database
-- that applied it would never see the change.
ALTER TABLE statelog_adoption DROP COLUMN ledger_folded;
