-- `statelog_adoption.ledger_folded` goes, because nothing reads it any more.
--
-- 0030 added it so the engine could fold, once, every adoption a build from
-- before the operation ledger travelled had recorded into the ledger's
-- watermark: such an adoption installed a file whose ledger its donor had
-- scrubbed. No build that scrubbed a ledger was ever released, so there is no
-- such adoption to fold, and the fold and the column that marked its progress
-- go together.
--
-- DROPPED IN THE COMMIT THAT STOPS THE WRITER NAMING IT: an insert naming a
-- column that is gone fails the adoption it records. There is no data to
-- migrate — the row is this node's history, and the column said nothing a
-- reader uses.
ALTER TABLE statelog_adoption DROP COLUMN ledger_folded;
