"""Event system — event types for the Crewlet engine."""

from crewlet.events.middleware import EventMiddleware
from crewlet.events.types import (
    A2AChannelClosed,
    A2AChannelOpened,
    A2AMessageDelivered,
    A2AMessageSent,
    AgentReassigned,
    AgentSpawned,
    AgentTerminated,
    BudgetExhausted,
    DocumentCreated,
    DocumentUpdated,
    Event,
    ExternalNotification,
    LLMUnavailable,
    MessageSent,
    OrgStarted,
    OrgStopped,
    RoleUpdated,
    ScheduledTaskFired,
    TaskAssigned,
    TaskCompleted,
    TaskCreated,
    TaskDelegated,
    TaskFailed,
    TaskStarted,
)

__all__ = [
    "A2AChannelClosed",
    "A2AChannelOpened",
    "A2AMessageDelivered",
    "A2AMessageSent",
    "AgentReassigned",
    "AgentSpawned",
    "AgentTerminated",
    "BudgetExhausted",
    "DocumentCreated",
    "DocumentUpdated",
    "Event",
    "EventMiddleware",
    "ExternalNotification",
    "LLMUnavailable",
    "MessageSent",
    "OrgStarted",
    "OrgStopped",
    "RoleUpdated",
    "ScheduledTaskFired",
    "TaskAssigned",
    "TaskCompleted",
    "TaskCreated",
    "TaskDelegated",
    "TaskFailed",
    "TaskStarted",
]
